version: '3.4'

services:
  linkshortener:
    image: ${DOCKER_REGISTRY-}linkshortener
    container_name: LinkShortener.Api
    build:
      context: .
      dockerfile: LinkShortener/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"

  linkshortener.db:
    image: postgres:latest
    container_name: linkshortener.db
    environment:
      - POSTGRES_DB=linkshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/linkshortener-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  linkshortener.cache:
    image: redis:latest
    container_name: linkshortener.cache
    restart: always
    ports:
      - '6379:6379'
  
  linkshortener.frontend:
    build:
      context: C:\Users\SillySharp\source\repos\reactfrontend
      dockerfile: Dockerfile
    image: linkshortener.react
    container_name: linkshortener.react
    ports:
      - "5173:5173"
    environment:
      - WATCHPACK_POLLING=true
    depends_on: 
      - linkshortener